name: Solar system workflow
on:
    push:
        branches:
            - main
            - 'features/*'
jobs:
    unit-testing:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: action/checkout@v4
        
        - name: Install Node js
          uses: action/setup-node@v3
          with:
            node-version: 18
        
        - name: Install dependencies
          run: npm install
        
        - name: Run tests
          run: npm test
