name: Solar system workflow
on:
    push:
        branches:
            - main
            - 'features/*'
env:
  MONGO_URI: ${{vars.MONGO_URI}}
  MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}
  MONGO_USERNAME: ${{vars.MONGO_USERNAME}}

jobs:
    unit-testing:
        strategy:
          matrix:
            node_version: [18, 19, 20]
            os: [ubuntu-latest, macos-latest] 
            exclude:
              - node_version: 18
                os: macos-latest

        runs-on: ${{matrix.os}}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        
        - name: Install Node js
          uses: actions/setup-node@v4
          with:
            node-version: ${{matrix.node_version}}
        
        - name: Cache dependencies
          id: npm-dependencies
          uses: actions/cache@v4
          with:
            path: node_modules
            key: ${{ matrix.os }}-node_modules-${{hashFiles('package-lock.json')}}
          

        - name: Install dependencies
          run: npm install
        
        - name: Run tests
          id: node-js-test
          run: npm test
        
        - name: Upload test result as artifact
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: Mocha_test_result_${{matrix.os}}_node_${{matrix.node_version}}
            path: test-results.xml
    
    code-coverage:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
          
        - name: Configure Node enviroment
          uses: actions/setup-node@v4
          with:
            node-version: 18
        
        - name: Cache dependencies
          id: npm-dependencies
          uses: actions/cache@v4
          with:
            path: node_modules
            key: ubuntu_latest-node_modules-${{hashFiles('package-lock.json')}}

        - name: Install Dependencies
          run: npm install

        - name: Run coverage
          continue-on-error: true
          run: npm run coverage

        - name: Archive test result
          uses: actions/upload-artifact@v4
          with:
            name: Coverage_result
            path: coverage